version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: basket-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: basket-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass sa
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: